### ISSUE TITLE
bug：LibAFL/libafl/src/events/mod.rs

### ISSUE THREAD

**Issue by zhjygit** [pr0me/SAFIREFUZZ#2]
error: unnecessary parentheses around match arm expression
   --> LibAFL/libafl/src/events/mod.rs:121:59
    |
121 |                 EventConfig::FromName { name_hash: b } => (a == b),
   改为： EventConfig::FromName { name_hash: b } => (a == b),

error: unnecessary parentheses around match arm expression
   --> LibAFL/libafl/src/events/mod.rs:128:51
    |
128 |                 EventConfig::BuildID { id: b } => (a == b),
    |                                                   ^      ^
    |
help: remove these parentheses
    |
128 -                 EventConfig::BuildID { id: b } => (a == b),
128 +                 EventConfig::BuildID { id: b } => a == b,

Just remove the parentheses.

**Comment by Acen28** [comment]
同学你好，我看你的issue收到了作者的回复，不知道你是否成功复现出来这个工具，如果可以的话能帮我看一下我的那个问题吗

**Comment by pr0me** [comment]
This is not a bug but a formatting error at the most.
The project should compile nonetheless, if you actually get that error during compilation, check that you do not pass `-Werror` or similar to cargo/rustc in any global config.

Hope this helps.
Otherwise, please post a complete error message, including the command you're running to produce it.
